<#
.SYNOPSIS
  deploy.ps1 — set up, build, and start Auxa (Work OS CRM) on Windows.

.DESCRIPTION
  Windows counterpart of deploy.sh. First run (no .env yet) launches an
  interactive setup wizard that asks for the environment variables — required
  ones first; optional integrations can be skipped and configured later in
  .env.

  TLS note: automatic certbot/Let's Encrypt setup is Linux-only (see
  deploy.sh). To expose a Windows machine publicly over HTTPS, put it behind
  a reverse proxy or tunnel (Cloudflare Tunnel, ngrok, IIS/win-acme) that
  terminates TLS and forwards to the port this script serves on.

.EXAMPLE
  .\deploy.ps1              # production: install, migrate, (seed if fresh), build, start
  .\deploy.ps1 -Dev         # development server
  .\deploy.ps1 -Setup       # (re)run the setup wizard (backs up existing .env)
  .\deploy.ps1 -Reset       # drop, re-migrate and re-seed the database
#>
[CmdletBinding()]
param(
  [switch]$Dev,        # run the dev server instead of a production build
  [switch]$Setup,      # (re)run the interactive setup wizard
  [switch]$Seed,       # (re)seed the database with demo data (destructive)
  [switch]$Reset,      # reset the database (drops + re-migrates + seeds)
  [switch]$NoInstall,  # skip dependency installation
  [switch]$NoBuild,    # skip the production build (prod mode only)
  [int]$Port = $(if ($env:PORT) { [int]$env:PORT } else { 3000 })
)

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

function Step($msg)  { Write-Host ""; Write-Host "> $msg" -ForegroundColor White }
function Info($msg)  { Write-Host "  $msg" -ForegroundColor DarkGray }
function Fail($msg)  { Write-Host "x $msg" -ForegroundColor Red; exit 1 }

# ---- prerequisites ----------------------------------------------------------
Step "Checking prerequisites"
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Fail "node is required — install it from https://nodejs.org"
}
Info "node $(node --version)"

$PM = $null
if (Get-Command pnpm -ErrorAction SilentlyContinue) { $PM = "pnpm" }
elseif (Get-Command npm -ErrorAction SilentlyContinue) { $PM = "npm" }
else { Fail "pnpm or npm is required" }
Info "package manager: $PM"

function New-Secret {
  node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
}

# ---- interactive setup wizard ----------------------------------------------
function Ask([string]$Question, [string]$Default = "") {
  if ($Default) {
    $answer = Read-Host "  $Question [$Default]"
  } else {
    $answer = Read-Host "  $Question"
  }
  if ([string]::IsNullOrWhiteSpace($answer)) { return $Default }
  return $answer.Trim()
}

function Invoke-Wizard {
  Step "Setup wizard"
  Info "Press Enter to accept the [default] or to skip an optional value."
  Info "Everything lands in .env — you can edit it again later."
  Write-Host ""

  Info "Required settings"
  $databaseUrl = Ask "Database URL (SQLite file works out of the box)" "file:./dev.db"
  $timezone    = Ask "App timezone" "Asia/Kolkata"
  $appUrl      = Ask "Public URL of the app (behind a tunnel/proxy, e.g. https://crm.example.com)" "http://localhost:$Port"
  $authSecret  = New-Secret
  Info "AUTH_SECRET: generated automatically"

  Write-Host ""
  Info "Optional integrations — Enter to skip any of these; the app runs"
  Info "without them (features degrade gracefully). Configure later in .env."
  $anthropicKey = Ask "Anthropic API key (AI features)" ""
  $resendKey    = Ask "Resend API key (outgoing email)" ""
  $emailFrom    = "Auxa <noreply@auxa.local>"
  if ($resendKey) { $emailFrom = Ask "Email From address" $emailFrom }
  $twilioSid    = Ask "Twilio Account SID (WhatsApp)" ""
  $twilioToken  = ""
  $twilioFrom   = ""
  if ($twilioSid) {
    $twilioToken = Ask "Twilio Auth Token" ""
    $twilioFrom  = Ask "Twilio WhatsApp From (e.g. whatsapp:+14155238886)" ""
  }
  $deepgramKey  = Ask "Deepgram API key (voice transcription)" ""
  $cronSecret   = New-Secret

  # Extra allowance for the public host (every origin is already accepted via
  # src/proxy.ts, so this is belt and braces).
  $allowedOrigins = ""
  try {
    $appHost = ([uri]$appUrl).Authority
    if ($appHost -notmatch "^(localhost|127\.0\.0\.1)") { $allowedOrigins = $appHost }
  } catch {}

  if (Test-Path .env) {
    $stamp = Get-Date -Format "yyyyMMddHHmmss"
    Copy-Item .env ".env.bak.$stamp"
    Info "existing .env backed up"
  }

  @"
# Generated by deploy.ps1 setup wizard. Safe to edit by hand.
DATABASE_URL="$databaseUrl"
AUTH_SECRET="$authSecret"
APP_URL="$appUrl"
APP_TIMEZONE="$timezone"

# Extra origins allowed to invoke Server Actions behind a proxy/tunnel
# (comma-separated). Every origin is already accepted via src/proxy.ts.
ALLOWED_ORIGINS="$allowedOrigins"

# Optional integrations — the app runs without these (features degrade gracefully).
ANTHROPIC_API_KEY="$anthropicKey"
ANTHROPIC_MODEL="claude-sonnet-4-5"
RESEND_API_KEY="$resendKey"
EMAIL_FROM="$emailFrom"
TWILIO_ACCOUNT_SID="$twilioSid"
TWILIO_AUTH_TOKEN="$twilioToken"
TWILIO_WHATSAPP_FROM="$twilioFrom"
WHATSAPP_VERIFY_TOKEN="auxa-verify"
DEEPGRAM_API_KEY="$deepgramKey"
CRON_SECRET="$cronSecret"
"@ | Set-Content -Path .env -Encoding UTF8
  Info "wrote .env"
}

# ---- environment ------------------------------------------------------------
Step "Preparing environment (.env)"
if ($Setup -or -not (Test-Path .env)) {
  Invoke-Wizard
} else {
  Info ".env already present — leaving it untouched (re-run with -Setup to change)"
}

# ---- dependencies -----------------------------------------------------------
if (-not $NoInstall) {
  Step "Installing dependencies"
  & $PM install
  if ($LASTEXITCODE -ne 0) { Fail "dependency installation failed" }
} else {
  Info "skipping install (-NoInstall)"
}

# ---- database ---------------------------------------------------------------
Step "Setting up the database"
$fresh = -not (Test-Path "prisma/dev.db")

npx prisma generate | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "prisma generate failed" }
Info "prisma client generated"

if ($Reset) {
  Info "resetting database (-Reset)"
  npx prisma migrate reset --force   # runs migrations + seed
  if ($LASTEXITCODE -ne 0) { Fail "database reset failed" }
} elseif ((Test-Path "prisma/migrations") -and (Get-ChildItem "prisma/migrations" -ErrorAction SilentlyContinue)) {
  npx prisma migrate deploy
  if ($LASTEXITCODE -ne 0) { Fail "migrations failed" }
  Info "migrations applied"
} else {
  npx prisma db push
  if ($LASTEXITCODE -ne 0) { Fail "schema push failed" }
  Info "schema pushed"
}

# Seed on first setup, or when explicitly requested (reset already seeds).
if (-not $Reset -and ($fresh -or $Seed)) {
  Step "Seeding demo data"
  & $PM run db:seed
  if ($LASTEXITCODE -ne 0) { Fail "seeding failed" }
}

# ---- build (prod) -----------------------------------------------------------
if (-not $Dev -and -not $NoBuild) {
  Step "Building for production"
  & $PM run build
  if ($LASTEXITCODE -ne 0) { Fail "build failed" }
}

# ---- start ------------------------------------------------------------------
$mode = if ($Dev) { "dev" } else { "prod" }
Step "Starting Auxa ($mode) on port $Port"
Write-Host ""
Write-Host "Auxa is running at http://localhost:$Port" -ForegroundColor White
Write-Host "  Sign in as the owner (password: auxa1234):"
Write-Host "    admin@auxa.app"
Write-Host "  Then create your team, clients, services and tasks from the app."
Write-Host ""

if ($Dev) {
  npx next dev -p $Port
} else {
  npx next start -p $Port
}
